const data = {
  products: [
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 60,
      brand: "Raymond",
      rating: 4.5,
      numReviwes: 10,
      countInShock: 20,
      description: "A popular shirt",
    },

    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 80,
      brand: "Zara",
      rating: 4.5,
      numReviwes: 10,
      countInShock: 20,
      description: "Awesome fit pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviwes: 10,
      countInShock: 20,
      description: "Awesome classic pants",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviwes: 10,
      countInShock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviwes: 10,
      countInShock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.1,
      numReviwes: 9,
      countInShock: 20,
      description: "A popular shirt",
    },
    ,
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 60,
      brand: "Raymond",
      rating: 4.5,
      numReviwes: 10,
      countInShock: 20,
      description: "A popular shirt",
    },

    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 80,
      brand: "Zara",
      rating: 4.5,
      numReviwes: 10,
      countInShock: 20,
      description: "Awesome fit pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviwes: 10,
      countInShock: 20,
      description: "Awesome classic pants",
    },
  ],
};


export default data;